# fly.toml app configuration file generated for puasa-sunnah-api on 2023-11-15T22:06:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "puasa-sunnah-api"
primary_region = "sin"

[build]
dockerfile = "Dockerfile"
build-target = "runtime"

[env]
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
