// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/granitebps/puasa-sunnah-api/pkg/core"
	"github.com/granitebps/puasa-sunnah-api/src/controller"
	"github.com/granitebps/puasa-sunnah-api/src/repository"
	"github.com/granitebps/puasa-sunnah-api/src/service"
)

// Injectors from wire.go:

func SetupDependencies(c *core.Core) *controller.ControllerStruct {
	sourceRepository := repository.NewSourceRepository(c)
	sourceService := service.NewSourceService(sourceRepository)
	typesRepository := repository.NewTypesRepository()
	typesService := service.NewTypesService(typesRepository)
	categoryRepository := repository.NewCategoryRepository(c)
	categoryService := service.NewCategoryService(categoryRepository)
	fastingRepository := repository.NewFastingRepository()
	fastingService := service.NewFastingService(fastingRepository, categoryRepository, typesRepository)
	adminService := service.NewAdminService(categoryRepository, sourceRepository)
	controllerStruct := controller.NewController(c, sourceService, typesService, categoryService, fastingService, adminService)
	return controllerStruct
}
