basePath: /
definitions:
  requests.CategoryRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  transformer.CategoryTransformer:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: lorem impsum
        type: string
    type: object
  types.Category:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: lorem impsum
        type: string
    type: object
  types.Fasting:
    properties:
      category:
        $ref: '#/definitions/types.Category'
      category_id:
        example: 1
        type: integer
      date:
        example: "2020-01-01"
        type: string
      day:
        example: 1
        type: integer
      id:
        example: 1
        type: integer
      month:
        example: 1
        type: integer
      type:
        $ref: '#/definitions/types.Type'
      type_id:
        example: 1
        type: integer
      year:
        example: 2020
        type: integer
    type: object
  types.Source:
    properties:
      id:
        example: 1
        type: integer
      url:
        example: https://granitebps.com
        type: string
    type: object
  types.Type:
    properties:
      description:
        example: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        type: string
      id:
        example: 1
        type: integer
      name:
        example: lorem
        type: string
    type: object
  utils.JSONResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
      timestamp:
        type: integer
    type: object
info:
  contact:
    email: granitebagas28@gmail.com
    name: Granite Bagas
  description: This is a Puasa Sunnah API Docs
  license:
    name: MIT
  title: Puasa Sunnah API
  version: "1.0"
paths:
  /api/v1/admin/categories:
    post:
      consumes:
      - application/json
      description: Create fasting category
      parameters:
      - description: JSON payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requests.CategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/utils.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/transformer.CategoryTransformer'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BasicAuth: []
      summary: Create category
      tags:
      - Admin
  /api/v1/admin/categories/:id:
    put:
      consumes:
      - application/json
      description: Update fasting category
      parameters:
      - description: JSON payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requests.CategoryRequest'
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/utils.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/transformer.CategoryTransformer'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      security:
      - BasicAuth: []
      summary: Update category
      tags:
      - Admin
  /api/v1/categories:
    get:
      consumes:
      - application/json
      description: Get list of categories
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/utils.JSONResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/types.Category'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: List Categories
      tags:
      - Categories
  /api/v1/fastings:
    get:
      consumes:
      - application/json
      description: Get list of sunnah fasting
      parameters:
      - description: Type ID
        in: query
        name: type_id
        type: integer
      - description: Category ID
        in: query
        name: category_id
        type: integer
      - description: Day in month
        in: query
        name: day
        type: integer
      - description: Month
        in: query
        name: month
        type: integer
      - description: Year
        in: query
        name: Year
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/utils.JSONResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/types.Fasting'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: List Sunnah Fastings
      tags:
      - Fastings
  /api/v1/sources:
    get:
      consumes:
      - application/json
      description: Get list of sources
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/utils.JSONResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/types.Source'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: List Sources
      tags:
      - Sources
  /api/v1/types:
    get:
      consumes:
      - application/json
      description: Get list of types
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/utils.JSONResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/types.Type'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.JSONResponse'
      summary: List Types
      tags:
      - Types
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
