package constants

// Environment Variable Constant
// Put env name in here to prevent typo
const (
	APP_NAME  = "APP_NAME"
	APP_ENV   = "APP_ENV"
	APP_DEBUG = "APP_DEBUG"
	APP_PORT  = "APP_PORT"
	APP_URL   = "APP_URL"

	DB_HOST = "DB_HOST"
	DB_PORT = "DB_PORT"
	DB_USER = "DB_USER"
	DB_PASS = "DB_PASS"
	DB_NAME = "DB_NAME"

	SENTRY_DSN = "SENTRY_DSN"

	NEWRELIC_ENABLED  = "NEWRELIC_ENABLED"
	NEWRELIC_APP_NAME = "NEWRELIC_APP_NAME"
	NEWRELIC_LICENSE  = "NEWRELIC_LICENSE"

	HEALTHCHECK_URL = "HEALTHCHECK_URL"

	ADMIN_USERNAME = "ADMIN_USERNAME"
	ADMIN_PASSWORD = "ADMIN_PASSWORD"

	AWS_ACCESS_KEY_ID     = "AWS_ACCESS_KEY_ID"
	AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
	AWS_DEFAULT_REGION    = "AWS_DEFAULT_REGION"
	AWS_BUCKET            = "AWS_BUCKET"

	MAILGUN_DOMAIN = "MAILGUN_DOMAIN"
	MAILGUN_SECRET = "MAILGUN_SECRET"
)
