name: CI/CD Test and Deploy API

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: false
      - name: Install dependencies
        run: go get .
      - name: Install test dependencies
        run: make deps_i
      - name: Test
        run: make test
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.60

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: |
          CGO_ENABLED=0 go build -ldflags="-w -s" -o api .
          CGO_ENABLED=0 go build -ldflags="-w -s" -o backup cmd/backup.go
      - name: Fetch .env File from Private Repo
        env:
          GIT_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Clone the private repo containing .env files
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/granitebps/env.git env-repo
      - name: SCP to Linode instance (API)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "api"
          target: "/root"
      - name: SCP to Linode instance (Backup)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "backup"
          target: "/root"
      - name: Transfer .env File to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: env-repo/puasa-sunnah/*
          target: /tmp/puasa-sunnah
      - name: Deploy API to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploying application ..."

            DEPLOY_DIR="/var/www/puasa-sunnah-api"
            TMP_ENV_DIR="/tmp/puasa-sunnah/env-repo/puasa-sunnah"
            ENV_FILE=".prod.env"

            if [ "${{ github.ref_name }}" = "dev" ]; then
              ENV_FILE=".dev.env"
            fi

            # Delete existing binary
            echo "Delete existing binary"
            sudo rm -R $DEPLOY_DIR/build/*

            # Move binary
            echo "Move new binary to build folder"
            sudo mv /root/api $DEPLOY_DIR/build/
            sudo mv /root/backup $DEPLOY_DIR/build/

            # Move the .env file into the deployment directory
            cp $TMP_ENV_DIR/$ENV_FILE $TMP_ENV_DIR/.env
            mv -f $TMP_ENV_DIR/.env $DEPLOY_DIR/.env

            # Restart the service
            echo "Restart Service"
            sudo service puasasunnah restart

            # Clean up temporary files
            rm -rf /tmp/puasa-sunnah

            echo "Application deployed!"
