name: CI/CD Test and Deploy API

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache: false
      - name: Install dependencies
        run: go get .
      - name: Install test dependencies
        run: make deps_i
      - name: Test
        run: make test
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.60

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: |
          CGO_ENABLED=0 go build -ldflags="-w -s" -o api .
          CGO_ENABLED=0 go build -ldflags="-w -s" -o backup cmd/backup.go
      - name: SCP to Linode instance (API)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "api"
          target: "/root"
      - name: SCP to Linode instance (Backup)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "backup"
          target: "/root"
      - name: Deploy API to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploying application ..."

            # Delete existing binary
            echo "Delete existing binary"
            sudo rm -R /var/www/puasa-sunnah-api/build/*

            # Move binary
            echo "Move new binary to build folder"
            sudo mv /root/api /var/www/puasa-sunnah-api/build/
            sudo mv /root/backup /var/www/puasa-sunnah-api/build/

            # Restart the service
            echo "Restart Service"
            sudo service puasasunnah restart

            echo "Application deployed!"